!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
!
!  Differentiation of individual_contribution in forward (tangent) mode (with options multiDirectional i4 dr8 r4):
!   variations   of useful results: p
!   with respect to varying inputs: psi
!   RW status of diff variables: psi:in p:out
SUBROUTINE INDIVIDUAL_CONTRIBUTION_DV(psi, psid, dn, asn, riskavn, &
& horizonn, p, pd, nbdirs)
!
  USE CONSTANTS
  USE OBSERVATIONS
  USE UTILITIES_DIFFV
  USE SP_DIFFV
  USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  IMPLICIT NONE
! 
! Ending subroutine and returning execution
! 
! 
! Declaring dummy variables
!   
! Vector of metaparameters
  REAL*8, INTENT(IN) :: psi(num_psi)
  REAL*8, INTENT(IN) :: psid(nbdirsmax, num_psi)
! Observed regime dummy
  INTEGER, INTENT(IN) :: dn
  REAL*8, INTENT(IN) :: asn
! Observed self-reported risk attitude
  INTEGER, INTENT(IN) :: riskavn
! Observed self-reported planning horizon
  INTEGER, INTENT(IN) :: horizonn
! Computed regime probability
  REAL*8, INTENT(OUT) :: p
  REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: pd
!
! Declaring external routines
!
! Trivariate normal cdf
  REAL*8, EXTERNAL :: TVTL
! Bivariate normal survival sdf
  REAL*8, EXTERNAL :: BVND
! Univariate normal cdf
  REAL*8, EXTERNAL :: PHID
! 
! Declaring local variables
! 
  REAL*8 :: m_s, m_q, m_z, m_y
  REAL*8, DIMENSION(nbdirsmax) :: m_sd, m_zd, m_yd
  REAL*8 :: sigma_s, sigma_z, sigma_y
  REAL*8, DIMENSION(nbdirsmax) :: sigma_sd, sigma_zd, sigma_yd
  REAL*8 :: rho_sz, rho_sy, rho_zy
  REAL*8, DIMENSION(nbdirsmax) :: rho_szd, rho_syd, rho_zyd
  REAL*8 :: gamma, kappa, q
  REAL*8, DIMENSION(nbdirsmax) :: qd
  REAL*8 :: delta_z(num_delta_z), delta_y(num_delta_y)
  REAL*8 :: delta_zd(nbdirsmax, num_delta_z), delta_yd(nbdirsmax, &
& num_delta_y)
  REAL*8 :: m_zs, m_ys, psi_z, psi_y, rho_psi_zy
  REAL*8, DIMENSION(nbdirsmax) :: m_zsd, m_ysd, psi_zd, psi_yd, &
& rho_psi_zyd
  REAL*8 :: p_as, p_zy, eps
  REAL*8, DIMENSION(nbdirsmax) :: p_asd, p_zyd
  REAL*8 :: limit3(3, 4), corr3(3), pcomp(4, 2)
  REAL*8 :: limit3d(nbdirsmax, 3, 4), corr3d(nbdirsmax, 3), pcompd(&
& nbdirsmax, 4, 2)
  INTRINSIC SQRT
  REAL*8 :: arg1
  REAL*8, DIMENSION(nbdirsmax) :: arg1d
  REAL*8 :: result1
  REAL*8, DIMENSION(nbdirsmax) :: result1d
  REAL*8 :: arg2
  REAL*8, DIMENSION(nbdirsmax) :: arg2d
  REAL*8 :: result2
  REAL*8, DIMENSION(nbdirsmax) :: result2d
  INTEGER :: nd
  INTEGER :: nbdirs
! 
! Beginning execution
! 
! Computing the b parameters
! 
  CALL COMPUTE_B_PARAMETERS_DV(psi, psid, m_s, m_sd, m_q, m_z, m_zd, m_y&
&                        , m_yd, sigma_s, sigma_sd, sigma_z, sigma_zd, &
&                        sigma_y, sigma_yd, rho_sz, rho_szd, rho_sy, &
&                        rho_syd, rho_zy, rho_zyd, gamma, kappa, q, qd, &
&                        delta_z, delta_zd, delta_y, delta_yd, nbdirs)
  pcomp = 0.d0
  limit3 = 0.d0
! 
! 
! Computing individual contribution to the loglikelihood
! 
  SELECT CASE  (dn) 
  CASE (1) 
    arg2 = 1.d0 - rho_sy**2
    DO nd=1,nbdirs
!
! 0 < as < 1          
! 
! density of a_s
! 
      arg1d(nd) = ((asn*qd(nd)-m_sd(nd))*sigma_s-(q*asn-m_s)*sigma_sd(nd&
&       ))/sigma_s**2
!
! probability of self-reported risk aversion and planning horizon
!
      m_zsd(nd) = m_zd(nd) + ((rho_szd(nd)*sigma_z+rho_sz*sigma_zd(nd))*&
&       sigma_s-rho_sz*sigma_z*sigma_sd(nd))*(m_s-q*asn)/sigma_s**2 + &
&       rho_sz*sigma_z*(m_sd(nd)-asn*qd(nd))/sigma_s
      m_ysd(nd) = m_yd(nd) + ((rho_syd(nd)*sigma_y+rho_sy*sigma_yd(nd))*&
&       sigma_s-rho_sy*sigma_y*sigma_sd(nd))*(m_s-q*asn)/sigma_s**2 + &
&       rho_sy*sigma_y*(m_sd(nd)-asn*qd(nd))/sigma_s
      arg2d(nd) = -(2*rho_sy*rho_syd(nd))
      IF (arg2 .EQ. 0.0) THEN
        result2d(nd) = 0.0_8
      ELSE
        result2d(nd) = arg2d(nd)/(2.0*SQRT(arg2))
      END IF
    END DO
    arg1 = (q*asn-m_s)/sigma_s
    CALL PDF_N01_DV(arg1, arg1d, result1, result1d, nbdirs)
    arg1 = 1.d0 - rho_sz**2
    DO nd=1,nbdirs
      p_asd(nd) = (result1d(nd)*sigma_s-result1*sigma_sd(nd))/sigma_s**2
      arg1d(nd) = -(2*rho_sz*rho_szd(nd))
      IF (arg1 .EQ. 0.0) THEN
        result1d(nd) = 0.0_8
      ELSE
        result1d(nd) = arg1d(nd)/(2.0*SQRT(arg1))
      END IF
      arg1d(nd) = -(2*rho_sy*rho_syd(nd))
    END DO
    p_as = result1/sigma_s
    m_zs = m_z + rho_sz*sigma_z/sigma_s*(m_s-q*asn)
    m_ys = m_y + rho_sy*sigma_y/sigma_s*(m_s-q*asn)
    result1 = SQRT(arg1)
    arg1 = 1.d0 - rho_sy**2
    DO nd=1,nbdirs
      psi_zd(nd) = sigma_zd(nd)*result1 + sigma_z*result1d(nd)
      IF (arg1 .EQ. 0.0) THEN
        result1d(nd) = 0.0_8
      ELSE
        result1d(nd) = arg1d(nd)/(2.0*SQRT(arg1))
      END IF
      arg1d(nd) = -(2*rho_sz*rho_szd(nd))
    END DO
    psi_z = sigma_z*result1
    result1 = SQRT(arg1)
    arg1 = 1.d0 - rho_sz**2
    DO nd=1,nbdirs
      psi_yd(nd) = sigma_yd(nd)*result1 + sigma_y*result1d(nd)
      IF (arg1 .EQ. 0.0) THEN
        result1d(nd) = 0.0_8
      ELSE
        result1d(nd) = arg1d(nd)/(2.0*SQRT(arg1))
      END IF
    END DO
    psi_y = sigma_y*result1
    result1 = SQRT(arg1)
    result2 = SQRT(arg2)
    DO nd=1,nbdirs
      rho_psi_zyd(nd) = ((rho_zyd(nd)-rho_szd(nd)*rho_sy-rho_sz*rho_syd(&
&       nd))*result1*result2-(rho_zy-rho_sz*rho_sy)*(result1d(nd)*&
&       result2+result1*result2d(nd)))/(result1*result2)**2
    END DO
    rho_psi_zy = (rho_zy-rho_sz*rho_sy)/(result1*result2)
!
    IF (riskavn .EQ. 1 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(1)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(2)-m_ys)/psi_y
      limit3(2, 3) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(1)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(3)-m_ys)/psi_y
      limit3(2, 3) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(2)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_zs)/psi_z
      limit3(2, 3) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(3)-m_ys)/psi_y
      CALL PHID_DV(limit3(2, 1), limit3d(:, 2, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(1)-m_ys)/psi_y
      limit3(2, 2) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 2) = (delta_y(1)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(2)-m_ys)/psi_y
      limit3(2, 2) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 2) = (delta_y(2)-m_ys)/psi_y
      limit3(2, 3) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(1)-m_ys)/psi_y
      limit3(2, 4) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 4) = (delta_y(1)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 1) = (delta_y(3)-m_ys)/psi_y
      limit3(2, 2) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 2) = (delta_y(3)-m_ys)/psi_y
      limit3(2, 3) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(2)-m_ys)/psi_y
      limit3(2, 4) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 4) = (delta_y(2)-m_ys)/psi_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_psi_zy, rho_psi_zyd, pcomp(1, 1), &
&            pcompd(:, 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zsd(nd))*psi_z-(delta_z(&
&         1)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_ysd(nd))*psi_y-(delta_y(&
&         3)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_zs)/psi_z
      limit3(2, 2) = (delta_z(1)-m_zs)/psi_z
      limit3(2, 3) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 3) = (delta_y(3)-m_ys)/psi_y
      limit3(2, 4) = (delta_z(1)-m_zs)/psi_z
      limit3(3, 4) = (delta_y(3)-m_ys)/psi_y
      CALL PHID_DV(limit3(2, 1), limit3d(:, 2, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL PHID_DV(limit3(2, 2), limit3d(:, 2, 2), pcomp(2, 1), pcompd(:&
&            , 2, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_psi_zy, rho_psi_zyd, pcomp(3, 1), &
&            pcompd(:, 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(1)-m_ys)/psi_y
      limit3(2, 2) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 2) = (delta_y(1)-m_ys)/psi_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_ysd(nd))*psi_y-(delta_y(&
&         2)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zsd(nd))*psi_z-(delta_z(&
&         2)-m_zs)*psi_zd(nd))/psi_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_ysd(nd))*psi_y-(delta_y(&
&         1)-m_ys)*psi_yd(nd))/psi_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(2)-m_ys)/psi_y
      limit3(2, 2) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 2) = (delta_y(2)-m_ys)/psi_y
      limit3(3, 3) = (delta_y(1)-m_ys)/psi_y
      limit3(2, 4) = (delta_z(2)-m_zs)/psi_z
      limit3(3, 4) = (delta_y(1)-m_ys)/psi_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(3)-m_y)/sigma_y
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(2)-m_y)/sigma_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_psi_zy, rho_psi_zyd, pcomp(2, 1), &
&            pcompd(:, 2, 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, :, :) = 0.0_8
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(3)-m_y)/sigma_y
      pcomp(1, 1) = 1.d0
      CALL PHID_DV(limit3(2, 2), limit3d(:, 2, 2), pcomp(2, 1), pcompd(:&
&            , 2, 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_psi_zy, rho_psi_zyd, pcomp(4, 1), &
&            pcompd(:, 4, 1), nbdirs)
!
    ELSE
      DO nd=1,nbdirs
        pcompd(nd, :, :) = 0.0_8
      END DO
    END IF
    DO nd=1,nbdirs
!
      p_zyd(nd) = pcompd(nd, 1, 1) - pcompd(nd, 2, 1) - pcompd(nd, 3, 1)&
&       + pcompd(nd, 4, 1)
    END DO
    p_zy = pcomp(1, 1) - pcomp(2, 1) - pcomp(3, 1) + pcomp(4, 1)
  CASE (2) 
! 
! as = 0
! 
! joint probability
! 
    p_zy = 1.d0
    DO nd=1,nbdirs
      corr3d(nd, :) = (/rho_szd(nd), rho_syd(nd), rho_zyd(nd)/)
      limit3d(nd, :, :) = 0.0_8
      limit3d(nd, 1, :) = -((m_sd(nd)*sigma_s-m_s*sigma_sd(nd))/sigma_s&
&       **2)
    END DO
    corr3 = (/rho_sz, rho_sy, rho_zy/)
    limit3(1, :) = -(m_s/sigma_s)
    eps = 1.d-13
!
    IF (riskavn .EQ. 1 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(2, 1), -&
&            limit3d(:, 2, 1), rho_sz, rho_szd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(1)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(1)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(2)-m_y)/sigma_y
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 1), pcompd(:, 1, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(3)-m_y)/sigma_y
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(2, 1), -&
&            limit3d(:, 2, 1), rho_sz, rho_szd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 2), -limit3d(:, 1, 2), -limit3(2, 2), -&
&            limit3d(:, 2, 2), rho_sz, rho_szd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 1), pcompd(:, 3, 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(2)-m_y)/sigma_y
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(3)-m_y)/sigma_y
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(2)-m_y)/sigma_y
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 1), pcompd(:, 2, 1), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(3)-m_y)/sigma_y
      pcomp(1, 1) = 1.d0
      CALL BVND_DV(-limit3(1, 2), -limit3d(:, 1, 2), -limit3(2, 2), -&
&            limit3d(:, 2, 2), rho_sz, rho_szd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 1), pcompd(:, 4, 1), nbdirs)
!
    ELSE
      DO nd=1,nbdirs
        pcompd(nd, :, :) = 0.0_8
      END DO
    END IF
    DO nd=1,nbdirs
!
      p_asd(nd) = pcompd(nd, 1, 1) - pcompd(nd, 2, 1) - pcompd(nd, 3, 1)&
&       + pcompd(nd, 4, 1)
    END DO
    p_as = pcomp(1, 1) - pcomp(2, 1) - pcomp(3, 1) + pcomp(4, 1)
    DO nd=1,nbdirs
      p_zyd(nd) = 0.0_8
    END DO
  CASE (3) 
! 
! as = 1
! 
! joint probability
! 
    p_zy = 1.d0
    DO nd=1,nbdirs
      corr3d(nd, :) = (/rho_szd(nd), rho_syd(nd), rho_zyd(nd)/)
      limit3d(nd, :, :) = 0.0_8
      limit3d(nd, 1, :) = ((qd(nd)-m_sd(nd))*sigma_s-(q-m_s)*sigma_sd(nd&
&       ))/sigma_s**2
    END DO
    corr3 = (/rho_sz, rho_sy, rho_zy/)
    limit3(1, :) = (q-m_s)/sigma_s
    eps = 1.d-13
!
    IF (riskavn .EQ. 1 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 1 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(1)-m_z)/sigma_z
      limit3(2, 3) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      CALL PHID_DV(limit3(2, 1), limit3d(:, 2, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(2, 1), -&
&            limit3d(:, 2, 1), rho_sz, rho_szd, pcomp(1, 2), pcompd(:, 1&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(1)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(2)-m_y)/sigma_y
      CALL BVND_DV(-limit3(2, 1), -limit3d(:, 2, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_zy, rho_zyd, pcomp(1, 1), pcompd(:, 1&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL TVTL_DV(0, limit3(:, 1), limit3d(:, :, 1), corr3, corr3d, eps&
&            , pcomp(1, 2), pcompd(:, 1, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 2 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 1) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 2, 3) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 1)-m_zd(nd))*sigma_z-(delta_z&
&         (1)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 1) = (delta_z(2)-m_z)/sigma_z
      limit3(2, 2) = (delta_z(1)-m_z)/sigma_z
      limit3(2, 3) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(1)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(3)-m_y)/sigma_y
      CALL PHID_DV(limit3(2, 1), limit3d(:, 2, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL PHID_DV(limit3(2, 2), limit3d(:, 2, 2), pcomp(2, 1), pcompd(:&
&            , 2, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 3), -limit3d(:, 2, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_zy, rho_zyd, pcomp(3, 1), pcompd(:, 3&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(2, 1), -&
&            limit3d(:, 2, 1), rho_sz, rho_szd, pcomp(1, 2), pcompd(:, 1&
&            , 2), nbdirs)
      CALL BVND_DV(-limit3(1, 2), -limit3d(:, 1, 2), -limit3(2, 2), -&
&            limit3d(:, 2, 2), rho_sz, rho_szd, pcomp(2, 2), pcompd(:, 2&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 3), limit3d(:, :, 3), corr3, corr3d, eps&
&            , pcomp(3, 2), pcompd(:, 3, 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 1) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(1)-m_y)/sigma_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 2), pcompd(:, 1&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 2) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 1)-m_yd(nd))*sigma_y-(delta_y&
&         (1)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(2)-m_y)/sigma_y
      limit3(3, 3) = (delta_y(1)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(1)-m_y)/sigma_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 2), pcompd(:, 1&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 2), pcompd(:, 3&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 3) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 3, 1) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 2) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 2)-m_yd(nd))*sigma_y-(delta_y&
&         (2)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(3, 1) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 2) = (delta_y(3)-m_y)/sigma_y
      limit3(3, 3) = (delta_y(2)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(2)-m_y)/sigma_y
      CALL PHID_DV(limit3(3, 1), limit3d(:, 3, 1), pcomp(1, 1), pcompd(:&
&            , 1, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 2), -limit3d(:, 2, 2), -limit3(3, 2), -&
&            limit3d(:, 3, 2), rho_zy, rho_zyd, pcomp(2, 1), pcompd(:, 2&
&            , 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL BVND_DV(-limit3(1, 1), -limit3d(:, 1, 1), -limit3(3, 1), -&
&            limit3d(:, 3, 1), rho_sy, rho_syd, pcomp(1, 2), pcompd(:, 1&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 2), limit3d(:, :, 2), corr3, corr3d, eps&
&            , pcomp(2, 2), pcompd(:, 2, 2), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 2), pcompd(:, 3&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE IF (riskavn .EQ. 3 .AND. horizonn .EQ. 4) THEN
      DO nd=1,nbdirs
!
        limit3d(nd, 2, 2) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 3) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        limit3d(nd, 2, 4) = ((delta_zd(nd, 2)-m_zd(nd))*sigma_z-(delta_z&
&         (2)-m_z)*sigma_zd(nd))/sigma_z**2
        limit3d(nd, 3, 4) = ((delta_yd(nd, 3)-m_yd(nd))*sigma_y-(delta_y&
&         (3)-m_y)*sigma_yd(nd))/sigma_y**2
        pcompd(nd, :, :) = 0.0_8
      END DO
      limit3(2, 2) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 3) = (delta_y(3)-m_y)/sigma_y
      limit3(2, 4) = (delta_z(2)-m_z)/sigma_z
      limit3(3, 4) = (delta_y(3)-m_y)/sigma_y
      pcomp(1, 1) = 1.d0
      CALL PHID_DV(limit3(2, 2), limit3d(:, 2, 2), pcomp(2, 1), pcompd(:&
&            , 2, 1), nbdirs)
      CALL PHID_DV(limit3(3, 3), limit3d(:, 3, 3), pcomp(3, 1), pcompd(:&
&            , 3, 1), nbdirs)
      CALL BVND_DV(-limit3(2, 4), -limit3d(:, 2, 4), -limit3(3, 4), -&
&            limit3d(:, 3, 4), rho_zy, rho_zyd, pcomp(4, 1), pcompd(:, 4&
&            , 1), nbdirs)
      CALL PHID_DV(limit3(1, 1), limit3d(:, 1, 1), pcomp(1, 2), pcompd(:&
&            , 1, 2), nbdirs)
      CALL BVND_DV(-limit3(1, 2), -limit3d(:, 1, 2), -limit3(2, 2), -&
&            limit3d(:, 2, 2), rho_sz, rho_szd, pcomp(2, 2), pcompd(:, 2&
&            , 2), nbdirs)
      CALL BVND_DV(-limit3(1, 3), -limit3d(:, 1, 3), -limit3(3, 3), -&
&            limit3d(:, 3, 3), rho_sy, rho_syd, pcomp(3, 2), pcompd(:, 3&
&            , 2), nbdirs)
      CALL TVTL_DV(0, limit3(:, 4), limit3d(:, :, 4), corr3, corr3d, eps&
&            , pcomp(4, 2), pcompd(:, 4, 2), nbdirs)
!
    ELSE
      DO nd=1,nbdirs
        pcompd(nd, :, :) = 0.0_8
      END DO
    END IF
    DO nd=1,nbdirs
!
      p_asd(nd) = pcompd(nd, 1, 1) - pcompd(nd, 2, 1) - pcompd(nd, 3, 1)&
&       + pcompd(nd, 4, 1) - pcompd(nd, 1, 2) + pcompd(nd, 2, 2) + &
&       pcompd(nd, 3, 2) - pcompd(nd, 4, 2)
    END DO
    p_as = pcomp(1, 1) - pcomp(2, 1) - pcomp(3, 1) + pcomp(4, 1) - (&
&     pcomp(1, 2)-pcomp(2, 2)-pcomp(3, 2)+pcomp(4, 2))
    DO nd=1,nbdirs
      p_zyd(nd) = 0.0_8
    END DO
  CASE DEFAULT
    DO nd=1,nbdirs
      p_asd(nd) = 0.0_8
      p_zyd(nd) = 0.0_8
    END DO
  END SELECT
  DO nd=1,nbdirs
!
! Evaluating the integrand
!
    pd(nd) = p_asd(nd)*p_zy + p_as*p_zyd(nd)
  END DO
  p = p_as*p_zy + minimum_p
END SUBROUTINE INDIVIDUAL_CONTRIBUTION_DV
