!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
!
MODULE UTILITIES_DIFFV
!
  USE CONSTANTS
  USE OBSERVATIONS
  USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
  IMPLICIT NONE
!
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!

CONTAINS
!
!
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  SUBROUTINE COMPUTE_PSI_PARAMETERS(xn_m_s, xn_m_q, xn_m_y, xn_sigma_s, &
&   theta, psi)
    IMPLICIT NONE
!
! Ending execution and returning control
!
!
! Declaring dummy variables
!
    REAL*8, INTENT(IN) :: xn_m_s(num_x_m_s)
    REAL*8, INTENT(IN) :: xn_m_q(num_x_m_q)
    REAL*8, INTENT(IN) :: xn_m_y(num_x_m_y)
    REAL*8, INTENT(IN) :: xn_sigma_s(num_x_sigma_s)
! Deep parameters
    REAL*8, INTENT(IN) :: theta(num_theta)
    REAL*8, INTENT(OUT) :: psi(num_psi)
!
! Declaring local parameters
!
    INTEGER :: il, iu, ipsi
    REAL*8 :: arg(num_tot_x)
    INTRINSIC SUM
!
! Beginning execution
!
! Metaparameters
!
! m_s
!
    arg = 0.d0
    il = 1
    iu = num_x_m_s
    arg(:num_x_m_s) = theta(il:iu)*xn_m_s
    psi(1) = SUM(arg)
!
! m_q
!
    arg = 0.d0
    il = iu + 1
    iu = iu + num_x_m_q
    arg(:num_x_m_q) = theta(il:iu)*xn_m_q
    psi(2) = SUM(arg)
!
! m_y
!
    arg = 0.d0
    il = iu + 1
    iu = iu + num_x_m_y
    arg(:num_x_m_y) = theta(il:iu)*xn_m_y
    psi(num_psi_m) = SUM(arg)
!
! sigma_s
!
    arg = 0.d0
    il = iu + 1
    iu = iu + num_x_sigma_s
    arg(:num_x_sigma_s) = theta(il:iu)*xn_sigma_s
    psi(num_psi_m+1) = SUM(arg)
    ipsi = num_psi_m + 1
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      psi(ipsi) = theta(il)
!
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      psi(ipsi) = theta(il)
!
    END IF
!
! rho_sz
!
    IF (switch_rho_sz .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      psi(ipsi) = theta(il)
!
    END IF
!
! rho_sy
!
    IF (switch_rho_sy .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      psi(ipsi) = theta(il)
!
    END IF
!
! rho_zy
!
    IF (switch_rho_zy .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      psi(ipsi) = theta(il)
!
    END IF
! 
! delta_z & delta_y
!
    psi(num_psi_m+num_psi_sigma+num_psi_rho+1:) = theta(num_theta_beta+&
&     num_theta_sigma_s+num_theta_sigma_z_y+num_theta_rho+1:)
  END SUBROUTINE COMPUTE_PSI_PARAMETERS
!  Differentiation of compute_b_parameters in forward (tangent) mode (with options multiDirectional i4 dr8 r4):
!   variations   of useful results: rho_zy m_s q m_y m_z sigma_s
!                sigma_y sigma_z delta_y delta_z rho_sy rho_sz
!   with respect to varying inputs: psi
!
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  SUBROUTINE COMPUTE_B_PARAMETERS_DV(psi, psid, m_s, m_sd, m_q, m_z, &
&   m_zd, m_y, m_yd, sigma_s, sigma_sd, sigma_z, sigma_zd, sigma_y, &
&   sigma_yd, rho_sz, rho_szd, rho_sy, rho_syd, rho_zy, rho_zyd, gamma, &
&   kappa, q, qd, delta_z, delta_zd, delta_y, delta_yd, nbdirs)
    USE DIFFSIZES
!  Hint: nbdirsmax should be the maximum number of differentiation directions
    IMPLICIT NONE
!
!
! Ending execution and returning control
!
!
! Declaring dummy variables
!
    REAL*8, INTENT(IN) :: psi(num_psi)
    REAL*8, INTENT(IN) :: psid(nbdirsmax, num_psi)
    REAL*8, INTENT(OUT) :: m_s
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: m_sd
    REAL*8, INTENT(OUT) :: m_q
    REAL*8, INTENT(OUT) :: m_z
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: m_zd
    REAL*8, INTENT(OUT) :: m_y
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: m_yd
    REAL*8, INTENT(OUT) :: sigma_s
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: sigma_sd
    REAL*8, INTENT(OUT) :: sigma_z
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: sigma_zd
    REAL*8, INTENT(OUT) :: sigma_y
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: sigma_yd
    REAL*8, INTENT(OUT) :: rho_sz
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: rho_szd
    REAL*8, INTENT(OUT) :: rho_sy
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: rho_syd
    REAL*8, INTENT(OUT) :: rho_zy
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: rho_zyd
    REAL*8, INTENT(OUT) :: gamma
    REAL*8, DIMENSION(nbdirsmax) :: gammad
    REAL*8, INTENT(OUT) :: kappa
    REAL*8, DIMENSION(nbdirsmax) :: kappad
    REAL*8, INTENT(OUT) :: q
    REAL*8, DIMENSION(nbdirsmax), INTENT(OUT) :: qd
    REAL*8, INTENT(OUT) :: delta_z(num_delta_z)
    REAL*8, INTENT(OUT) :: delta_zd(nbdirsmax, num_delta_z)
    REAL*8, INTENT(OUT) :: delta_y(num_delta_y)
    REAL*8, INTENT(OUT) :: delta_yd(nbdirsmax, num_delta_y)
!
! Declaring local variables
!
    INTEGER :: ipsi, il, iu, i
    INTRINSIC EXP
    INTRINSIC LOG
    INTRINSIC ATAN
    INTRINSIC SQRT
    REAL*8 :: arg1
    REAL*8, DIMENSION(nbdirsmax) :: arg1d
    REAL*8 :: result1
    REAL*8, DIMENSION(nbdirsmax) :: result1d
    INTEGER :: nd
    INTEGER :: nbdirs
    q = EXP(psi(2))
    kappa = EXP(psi(3))
    gamma = (q+kappa/apriori_t)/(1.d0+kappa/apriori_t)
    DO nd=1,nbdirs
!
! Beginning 
!
! Beginning execution
! 
! means
!
      m_sd(nd) = psid(nd, 1)
      m_yd(nd) = psid(nd, 3)
!
! risk aversion and planning horizon
!
      qd(nd) = psid(nd, 2)*EXP(psi(2))
      kappad(nd) = psid(nd, 3)*EXP(psi(3))
      gammad(nd) = ((qd(nd)+kappad(nd)/apriori_t)*(1.d0+kappa/apriori_t)&
&       -(q+kappa/apriori_t)*kappad(nd)/apriori_t)/(1.d0+kappa/apriori_t&
&       )**2
      m_zd(nd) = gammad(nd)/gamma
!
! sigma_s
!
      sigma_sd(nd) = psid(nd, num_psi_m+1)*EXP(psi(num_psi_m+1))
    END DO
    m_s = psi(1)
    m_q = psi(2)
    m_y = psi(3)
    m_z = LOG(gamma)
    sigma_s = minimum_sigma_s+EXP(psi(num_psi_m+1))
    ipsi = num_psi_m + 1
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      ipsi = ipsi + 1
      DO nd=1,nbdirs
        sigma_zd(nd) = psid(nd, ipsi)*EXP(psi(ipsi))
      END DO
      sigma_z = EXP(psi(ipsi))
!
    ELSE IF (switch_sigma_z .EQ. 0) THEN
!
      sigma_z = 1.d0
!
      DO nd=1,nbdirs
        sigma_zd(nd) = 0.0_8
      END DO
    ELSE
      DO nd=1,nbdirs
        sigma_zd(nd) = 0.0_8
      END DO
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      ipsi = ipsi + 1
      DO nd=1,nbdirs
        sigma_yd(nd) = psid(nd, ipsi)*EXP(psi(ipsi))
      END DO
      sigma_y = EXP(psi(ipsi))
!
    ELSE IF (switch_sigma_y .EQ. 0) THEN
!
      sigma_y = 1.d0
!
      DO nd=1,nbdirs
        sigma_yd(nd) = 0.0_8
      END DO
    ELSE
      DO nd=1,nbdirs
        sigma_yd(nd) = 0.0_8
      END DO
    END IF
!
! rho_sz
!
    IF (switch_rho_sz .EQ. 1) THEN
!
      ipsi = ipsi + 1
      DO nd=1,nbdirs
        rho_szd(nd) = twooverpi*psid(nd, ipsi)/(1.0+psi(ipsi)**2)
      END DO
      rho_sz = twooverpi*ATAN(psi(ipsi))
!
    ELSE IF (switch_rho_sz .EQ. 0) THEN
!
      rho_sz = 0.d0
!
      DO nd=1,nbdirs
        rho_szd(nd) = 0.0_8
      END DO
    ELSE
      DO nd=1,nbdirs
        rho_szd(nd) = 0.0_8
      END DO
    END IF
!
! rho_sy
!
    IF (switch_rho_sy .EQ. 1) THEN
!
      ipsi = ipsi + 1
      DO nd=1,nbdirs
        rho_syd(nd) = twooverpi*psid(nd, ipsi)/(1.0+psi(ipsi)**2)
      END DO
      rho_sy = twooverpi*ATAN(psi(ipsi))
!
    ELSE IF (switch_rho_sy .EQ. 0) THEN
!
      rho_sy = 0.d0
!
      DO nd=1,nbdirs
        rho_syd(nd) = 0.0_8
      END DO
    ELSE
      DO nd=1,nbdirs
        rho_syd(nd) = 0.0_8
      END DO
    END IF
!
! rho_zy
!
    IF (switch_rho_zy .EQ. 1) THEN
!
      ipsi = ipsi + 1
      arg1 = (1.d0-rho_sz**2)*(1.d0-rho_sy**2)
      result1 = SQRT(arg1)
      DO nd=1,nbdirs
        arg1d(nd) = -(2*rho_sz*rho_szd(nd)*(1.d0-rho_sy**2)) - (1.d0-&
&         rho_sz**2)*2*rho_sy*rho_syd(nd)
        IF (arg1 .EQ. 0.0) THEN
          result1d(nd) = 0.0_8
        ELSE
          result1d(nd) = arg1d(nd)/(2.0*SQRT(arg1))
        END IF
        rho_zyd(nd) = rho_szd(nd)*rho_sy + rho_sz*rho_syd(nd) + &
&         twooverpi*(result1d(nd)*ATAN(psi(ipsi))+result1*psid(nd, ipsi)&
&         /(1.0+psi(ipsi)**2))
      END DO
      rho_zy = rho_sz*rho_sy + result1*twooverpi*ATAN(psi(ipsi))
!
    ELSE
      DO nd=1,nbdirs
        rho_zyd(nd) = 0.0_8
      END DO
    END IF
!
! delta_z
!
    il = ipsi
    delta_z(1) = 0.d0
    DO nd=1,nbdirs
      delta_zd(nd, :) = 0.0_8
      delta_zd(nd, 2:) = psid(nd, il+1:il+num_theta_delta_z)*EXP(psi(il+&
&       1:il+num_theta_delta_z))
    END DO
    delta_z(2:) = EXP(psi(il+1:il+num_theta_delta_z))
    DO i=3,num_delta_z
      DO nd=1,nbdirs
!
        delta_zd(nd, i) = delta_zd(nd, i) + delta_zd(nd, i-1)
      END DO
      delta_z(i) = delta_z(i) + delta_z(i-1)
    END DO
!
!
! delta_y
!
    il = il + num_theta_delta_z
    delta_y(1) = 0.d0
    DO nd=1,nbdirs
      delta_yd(nd, :) = 0.0_8
      delta_yd(nd, 2:) = psid(nd, il+1:il+num_theta_delta_y)*EXP(psi(il+&
&       1:il+num_theta_delta_y))
    END DO
    delta_y(2:) = EXP(psi(il+1:il+num_theta_delta_y))
    DO i=3,num_delta_y
      DO nd=1,nbdirs
!
        delta_yd(nd, i) = delta_yd(nd, i) + delta_yd(nd, i-1)
      END DO
      delta_y(i) = delta_y(i) + delta_y(i-1)
    END DO
  END SUBROUTINE COMPUTE_B_PARAMETERS_DV
!
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  SUBROUTINE COMPUTE_B_PARAMETERS(psi, m_s, m_q, m_z, m_y, sigma_s, &
&   sigma_z, sigma_y, rho_sz, rho_sy, rho_zy, gamma, kappa, q, delta_z, &
&   delta_y)
    IMPLICIT NONE
!
!
! Ending execution and returning control
!
!
! Declaring dummy variables
!
    REAL*8, INTENT(IN) :: psi(num_psi)
    REAL*8, INTENT(OUT) :: m_s
    REAL*8, INTENT(OUT) :: m_q
    REAL*8, INTENT(OUT) :: m_z
    REAL*8, INTENT(OUT) :: m_y
    REAL*8, INTENT(OUT) :: sigma_s
    REAL*8, INTENT(OUT) :: sigma_z
    REAL*8, INTENT(OUT) :: sigma_y
    REAL*8, INTENT(OUT) :: rho_sz
    REAL*8, INTENT(OUT) :: rho_sy
    REAL*8, INTENT(OUT) :: rho_zy
    REAL*8, INTENT(OUT) :: gamma
    REAL*8, INTENT(OUT) :: kappa
    REAL*8, INTENT(OUT) :: q
    REAL*8, INTENT(OUT) :: delta_z(num_delta_z)
    REAL*8, INTENT(OUT) :: delta_y(num_delta_y)
!
! Declaring local variables
!
    INTEGER :: ipsi, il, iu, i
    INTRINSIC EXP
    INTRINSIC LOG
    INTRINSIC ATAN
    INTRINSIC SQRT
    REAL*8 :: arg1
    REAL*8 :: result1
!
! Beginning 
!
! Beginning execution
! 
! means
!
    m_s = psi(1)
    m_q = psi(2)
    m_y = psi(3)
!
! risk aversion and planning horizon
!
    q = EXP(psi(2))
    kappa = EXP(psi(3))
    gamma = (q+kappa/apriori_t)/(1.d0+kappa/apriori_t)
    m_z = LOG(gamma)
!
! sigma_s
!
    sigma_s = minimum_sigma_s+EXP(psi(num_psi_m+1))
    ipsi = num_psi_m + 1
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      ipsi = ipsi + 1
      sigma_z = EXP(psi(ipsi))
!
    ELSE IF (switch_sigma_z .EQ. 0) THEN
!
      sigma_z = 1.d0
!
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      ipsi = ipsi + 1
      sigma_y = EXP(psi(ipsi))
!
    ELSE IF (switch_sigma_y .EQ. 0) THEN
!
      sigma_y = 1.d0
!
    END IF
!
! rho_sz
!
    IF (switch_rho_sz .EQ. 1) THEN
!
      ipsi = ipsi + 1
      rho_sz = twooverpi*ATAN(psi(ipsi))
!
    ELSE IF (switch_rho_sz .EQ. 0) THEN
!
      rho_sz = 0.d0
!
    END IF
!
! rho_sy
!
    IF (switch_rho_sy .EQ. 1) THEN
!
      ipsi = ipsi + 1
      rho_sy = twooverpi*ATAN(psi(ipsi))
!
    ELSE IF (switch_rho_sy .EQ. 0) THEN
!
      rho_sy = 0.d0
!
    END IF
!
! rho_zy
!
    IF (switch_rho_zy .EQ. 1) THEN
!
      ipsi = ipsi + 1
      arg1 = (1.d0-rho_sz**2)*(1.d0-rho_sy**2)
      result1 = SQRT(arg1)
      rho_zy = rho_sz*rho_sy + result1*twooverpi*ATAN(psi(ipsi))
!
    END IF
!
! delta_z
!
    il = ipsi
    delta_z(1) = 0.d0
    delta_z(2:) = EXP(psi(il+1:il+num_theta_delta_z))
    DO i=3,num_delta_z
!
      delta_z(i) = delta_z(i) + delta_z(i-1)
    END DO
!
!
! delta_y
!
    il = il + num_theta_delta_z
    delta_y(1) = 0.d0
    delta_y(2:) = EXP(psi(il+1:il+num_theta_delta_y))
    DO i=3,num_delta_y
!
      delta_y(i) = delta_y(i) + delta_y(i-1)
    END DO
  END SUBROUTINE COMPUTE_B_PARAMETERS
!
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!
  SUBROUTINE COMPUTE_THETAF_PARAMETERS(theta, thetaf)
    IMPLICIT NONE
!
!
! Ending execution and returning control
!
!
! Declaring dummy variables
!
    REAL*8, INTENT(IN) :: theta(num_theta)
    REAL*8, INTENT(OUT) :: thetaf(num_theta)
!
! Declaring local variables
!
    INTEGER :: i, iu
    REAL*8 :: rho_sz, rho_sy
    INTRINSIC EXP
    INTRINSIC ATAN
    INTRINSIC SQRT
    REAL*8 :: arg1
    REAL*8 :: result1
! 
! Beginning execution
! 
! thetaF = theta for the parameters in the means and in sigma_s
!
    DO i=1,num_theta_beta+num_theta_sigma_s
!
      thetaf(i) = theta(i)
    END DO
!
    iu = num_theta_beta + num_theta_sigma_s
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      iu = iu + 1
      thetaf(iu) = EXP(theta(iu))
!
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      iu = iu + 1
      thetaf(iu) = EXP(theta(iu))
!
    END IF
!
! rho_sz
!
    IF (switch_rho_sz .EQ. 1) THEN
!
      iu = iu + 1
      rho_sz = twooverpi*ATAN(theta(iu))
      thetaf(iu) = rho_sz
!
    ELSE IF (switch_rho_sz .EQ. 0) THEN
!
      rho_sz = 0.d0
!
    END IF
!
! rho_sy
!
    IF (switch_rho_sy .EQ. 1) THEN
!
      iu = iu + 1
      rho_sy = twooverpi*ATAN(theta(iu))
      thetaf(iu) = rho_sy
!
    ELSE IF (switch_rho_sy .EQ. 0) THEN
!
      rho_sy = 0.d0
!
    END IF
!
! rho_zy
!
    IF (switch_rho_zy .EQ. 1) THEN
!
      iu = iu + 1
      arg1 = (1.d0-rho_sz**2)*(1.d0-rho_sy**2)
      result1 = SQRT(arg1)
      thetaf(iu) = rho_sz*rho_sy + result1*twooverpi*ATAN(theta(iu))
!
    END IF
!
! delta_z
!
    thetaf(iu+1:iu+num_theta_delta_z) = EXP(theta(iu+1:iu+&
&     num_theta_delta_z))
    DO i=iu+2,iu+num_theta_delta_z
!
      thetaf(i) = thetaf(i) + thetaf(i-1)
    END DO
!
    iu = iu + num_theta_delta_z
!
! delta_y
!
    thetaf(iu+1:iu+num_theta_delta_y) = EXP(theta(iu+1:iu+&
&     num_theta_delta_y))
    DO i=iu+2,iu+num_theta_delta_y
!
      thetaf(i) = thetaf(i) + thetaf(i-1)
    END DO
  END SUBROUTINE COMPUTE_THETAF_PARAMETERS
! 
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
! 
  FUNCTION MATRIX_DTHETA_DPSIPRIME(xn_m_s, xn_m_q, xn_m_y, xn_sigma_s, &
&   theta)
    IMPLICIT NONE
!
! 
! Ending execution and returning control
! 
!
! Declaring dummy variables
! 
    REAL*8, INTENT(IN) :: xn_m_s(num_x_m_s)
    REAL*8, INTENT(IN) :: xn_m_q(num_x_m_q)
    REAL*8, INTENT(IN) :: xn_m_y(num_x_m_y)
    REAL*8, INTENT(IN) :: xn_sigma_s(num_x_sigma_s)
! Deep parameters
    REAL*8, INTENT(IN) :: theta(num_theta)
!
! Declaring local variables
!
    INTEGER :: il, iu, ipsi, i
! 
! Declaring function type
! 
    REAL*8 :: matrix_dtheta_dpsiprime(num_theta, num_psi)
! 
! Beginning execution
! 
! Initialising matrix_dtheta_dpsiprime
! 
    matrix_dtheta_dpsiprime = 0.d0
!
! beta_m_s
!
    il = 1
    iu = num_x_m_s
    matrix_dtheta_dpsiprime(il:iu, 1) = xn_m_s
!
! beta_m_q
!
    il = iu + 1
    iu = iu + num_x_m_q
    matrix_dtheta_dpsiprime(il:iu, 2) = xn_m_q
!
! beta_m_y
!
    il = iu + 1
    iu = iu + num_x_m_y
    matrix_dtheta_dpsiprime(il:iu, 3) = xn_m_y
!
! beta_sigma_s
!
    il = iu + 1
    iu = iu + num_x_sigma_s
    matrix_dtheta_dpsiprime(il:iu, 4) = xn_sigma_s
    ipsi = 4
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
!
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
!
    END IF
!
! rho_sz
!
    IF (switch_rho_sz .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
!
    END IF
!
! rho_sy
!
    IF (switch_rho_sy .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
!
    END IF
!
! rho_zy
!
    IF (switch_rho_zy .EQ. 1) THEN
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
!
    END IF
!
! delta_z
!
    DO i=1,num_theta_delta_z
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
    END DO
!
!
! delta_y
!
    DO i=1,num_theta_delta_y
!
      il = iu + 1
      iu = il
      ipsi = ipsi + 1
      matrix_dtheta_dpsiprime(iu, ipsi) = 1.d0
    END DO
  END FUNCTION MATRIX_DTHETA_DPSIPRIME
! 
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
! 
  FUNCTION MATRIX_DTHETAF_DTHETAPRIME(theta)
    IMPLICIT NONE
!
! 
! Ending execution and returning control
! 
! 
! Declaring dummy variables
! 
    REAL*8, INTENT(IN) :: theta(num_theta)
! 
! Declaring function type
! 
    REAL*8 :: matrix_dthetaf_dthetaprime(num_theta, num_theta)
!
! Declaring local variables
!
    INTEGER :: i, iu
    REAL*8 :: rho_sz, rho_sy, rho_zy
    INTRINSIC EXP
    INTRINSIC ATAN
    INTRINSIC SQRT
    REAL*8 :: arg1
    REAL*8 :: result1
! 
! Beginning execution
! 
! Initialising matrix_dtheta_dbprime
! 
    matrix_dthetaf_dthetaprime = 0.d0
!
! Unit diagonal block for the parameters in the means and in sigma_s
!
    DO i=1,num_theta_beta+num_theta_sigma_s
!
      matrix_dthetaf_dthetaprime(i, i) = 1.d0
    END DO
!
    iu = num_theta_beta + num_theta_sigma_s
!
! sigma_z
!
    IF (switch_sigma_z .EQ. 1) THEN
!
      iu = iu + 1
      matrix_dthetaf_dthetaprime(iu, iu) = EXP(theta(iu))
!
    END IF
!
! sigma_y
!
    IF (switch_sigma_y .EQ. 1) THEN
!
      iu = iu + 1
      matrix_dthetaf_dthetaprime(iu, iu) = EXP(theta(iu))
!
    END IF
!
! Correlation parameters
!
    IF (switch_rho_sz .EQ. 1 .AND. switch_rho_sy .EQ. 1) THEN
!
      rho_sz = twooverpi*ATAN(theta(iu+1))
      rho_sy = twooverpi*ATAN(theta(iu+2))
      arg1 = (1.d0-rho_sz**2)*(1.d0-rho_sy**2)
      result1 = SQRT(arg1)
      rho_zy = rho_sz*rho_sy + result1*twooverpi*ATAN(theta(iu+3))
      matrix_dthetaf_dthetaprime(iu+1, iu+1) = twooverpi/(1.d0+theta(iu+&
&       1)**2)
      matrix_dthetaf_dthetaprime(iu+3, iu+1) = twooverpi/(1.d0+theta(iu+&
&       1)**2)*(rho_sy-rho_sz*(rho_zy-rho_sz*rho_sy)/(1.d0-rho_sz**2))
      matrix_dthetaf_dthetaprime(iu+2, iu+2) = twooverpi/(1.d0+theta(iu+&
&       2)**2)
      matrix_dthetaf_dthetaprime(iu+3, iu+2) = twooverpi/(1.d0+theta(iu+&
&       2)**2)*(rho_sz-rho_sy*(rho_zy-rho_sz*rho_sy)/(1.d0-rho_sy**2))
      arg1 = (1.d0-rho_sz**2)*(1.d0-rho_sy**2)
      result1 = SQRT(arg1)
      matrix_dthetaf_dthetaprime(iu+3, iu+3) = twooverpi/(1.d0+theta(iu+&
&       3)**2)*result1
      iu = iu + 3
!
    ELSE IF (switch_rho_sz .EQ. 1 .AND. switch_rho_sy .EQ. 0) THEN
!
      rho_sz = twooverpi*ATAN(theta(iu+1))
      arg1 = 1.d0 - rho_sz**2
      result1 = SQRT(arg1)
      rho_zy = result1*twooverpi*ATAN(theta(iu+2))
      matrix_dthetaf_dthetaprime(iu+1, iu+1) = twooverpi/(1.d0+theta(iu+&
&       1)**2)
      matrix_dthetaf_dthetaprime(iu+2, iu+1) = -(twooverpi/(1.d0+theta(&
&       iu+1)**2)*rho_sz*rho_zy/(1.d0-rho_sz**2))
      arg1 = 1.d0 - rho_sz**2
      result1 = SQRT(arg1)
      matrix_dthetaf_dthetaprime(iu+2, iu+2) = twooverpi/(1.d0+theta(iu+&
&       2)**2)*result1
      iu = iu + 2
!
    ELSE IF (switch_rho_sz .EQ. 0 .AND. switch_rho_sy .EQ. 1) THEN
!
      rho_sy = twooverpi*ATAN(theta(iu+1))
      arg1 = 1.d0 - rho_sy**2
      result1 = SQRT(arg1)
      rho_zy = result1*twooverpi*ATAN(theta(iu+2))
      matrix_dthetaf_dthetaprime(iu+1, iu+1) = twooverpi/(1.d0+theta(iu+&
&       1)**2)
      matrix_dthetaf_dthetaprime(iu+2, iu+1) = -(twooverpi/(1.d0+theta(&
&       iu+1)**2)*rho_sy*rho_zy/(1.d0-rho_sy**2))
      arg1 = 1.d0 - rho_sy**2
      result1 = SQRT(arg1)
      matrix_dthetaf_dthetaprime(iu+2, iu+2) = twooverpi/(1.d0+theta(iu+&
&       2)**2)*result1
      iu = iu + 2
!
    ELSE IF (switch_rho_sz .EQ. 0 .AND. switch_rho_sy .EQ. 0) THEN
!
      rho_zy = twooverpi*ATAN(theta(iu+1))
      matrix_dthetaf_dthetaprime(iu+1, iu+1) = twooverpi/(1.d0+theta(iu+&
&       1)**2)
!
    END IF
!
! delta_z
!
    DO i=iu+1,iu+num_theta_delta_z
!
      matrix_dthetaf_dthetaprime(i:iu+num_theta_delta_z, i) = EXP(theta(&
&       i))
    END DO
!
    iu = iu + num_theta_delta_z
!
! delta_y
!
    DO i=iu+1,iu+num_theta_delta_y
!
      matrix_dthetaf_dthetaprime(i:iu+num_theta_delta_y, i) = EXP(theta(&
&       i))
    END DO
  END FUNCTION MATRIX_DTHETAF_DTHETAPRIME
END MODULE UTILITIES_DIFFV
